name: origin
favicon: null
layout_spectrum: 0.43145
typography_spectrum: 0.48554
title: Los Angeles Orgy Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1efd7'
    - '#5a3d7d'
    - '#43708b'
    - '#fcc253'
    - '#2fe1e1'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.8755757538601756
  rhythmicContrast: 1
purpose: []
