analytics: {}
color:
  brandColors:
    - '#F1EFD7'
    - '#5A3D7D'
    - '#43708B'
    - '#FCC253'
    - '#2FE1E1'
  brandStrength: 0
  lightness: 0.508446
  rhythmicContrast: 0.494932
  saturation: 0.97973
cta: {}
layout_spectrum: 0.199324
name: origin
opengraph: {}
purpose: []
typography_spectrum: 0.48554
