analytics: {}
color:
  brandColors:
    - '#f1efd7'
    - '#5a3d7d'
    - '#43708b'
    - '#fcc253'
    - '#2fe1e1'
  brandStrength: 0
  lightness: 0.5625
  rhythmicContrast: 1
  saturation: 0.0625
cta: {}
layout_spectrum: 1
name: origin
opengraph: {}
purpose: []
typography_spectrum: 0.48554
